# -*- coding: utf-8 -*-
"""Assignment-9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MzVYYLJBg4EagDwG1793x0kYmiBAR6w9
"""

import numpy as np
A = ([[1,-1],[2,3]])
print("Original matrix:")
print(A)
result =  np.linalg.inv(A)
print("Inverse of the said matrix:")
print(result)