# -*- coding: utf-8 -*-
"""Assignment-9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HbcRpRsLt7h6FExvEYK8OTuG8RqSWGhd
"""

import numpy as np
  
  
# Original matrix
matrix1 = np.array([[1, -1], [2, 3]])
print(matrix1)
  
# Decomposition of the said matrix
q, r = np.linalg.qr(matrix1)
print('\nQ:\n', q)
print('\nR:\n', r)